<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Create User' => 'Novo usuário',
    'Delete' => 'Excluir',
    'Email' => '',
    'ID' => '',
    'Reset' => '',
    'Save' => 'Salvar',
    'Search' => 'Buscar',
    'Status' => '',
    'Superadmin' => '',
    'The requested page does not exist.' => '',
    'Update' => 'Atualizar',
    'Update User: mode' => 'Atualizar usuário',
    'Users' => 'Usuários',
    'Auth Key' => 'Chave de autenticação',
    'Created At' => 'Criado em',
    'Password Hash' => 'Hash de senha',
    'Password Reset Token' => 'Token de alteração de senha',
    'Updated At' => 'Atualizado em',
    'Username' => 'Usuário',
    'Active' => 'Ativo',
    'Deleted' => 'Bloqueado',
    'Unconfirmed' => 'Não confirmado',
    'Role created successfully' => 'Função criada com sucesso',
    'Role deleted successfully' => 'Função removida com sucesso',
    'Create' => 'Criar',
    'Role' => 'Função',
    'Roles' => 'Funções',
    'Permission' => 'Permissão',
    'Permissions' => 'Permissões',
    'Create Role' => 'Criar Função',
    'Item name must be unique. [{name}] already exists' => 'Nome do item deve ser único. [{name}] já existe.',
    'Name' => 'Nome',
    'Description' => 'Descrição',
    'Rule' => 'Regra',
    'Select' => 'Selecione',
    'Items' => 'Itens',
];
